### ISSUE TITLE
Package at packages.vmware.com..etc. could not be installed

### ISSUE THREAD

**Issue by georgepatterson** [ruzickap/ansible-role-vmwaretools#1]
The requested file was http://packages.vmware.com/tools/esx/latest/repos/vmware-tools-repo-RHEL6-9.0.15-1.el6.x86_64.rpm and it doesn't exist on that server.

All is well up until this point...

```
TASK: [peru.vmwaretools | Install vmware-tools repository.] *******************
failed: [ans01] => {"changed": false, "failed": true, "rc": 1}
msg: Package at http://packages.vmware.com/tools/esx/latest/repos/vmware-tools-repo-RHEL6-9.0.15-1.el6.x86_64.rpm could not be installed

FATAL: all hosts have already failed -- aborting
```

Not sure of the best way to deal with this but I changed the following line from
vmwaretools_repo_version: 9.0.15-1
to
vmwaretools_repo_version: 9.10.1-1

These tasks then worked like a treat. This hasn't been checked for other ditributions nor other release is of Centos6/ RHEL6. I could be persuaded to maintain this as part of my work, assuming that there is demand for this project.

**Comment by ruzickap** [comment]
Hello.

Thank you for reporting it. I fixed it in the latest commit.
I have no idea how to do it automatically without manually changing the parameter.

Thank you

PetrR
