### ISSUE TITLE
Installing vmware tools from repo fails during GPG check

### ISSUE THREAD

**Issue by jblankenship30** [ruzickap/ansible-role-vmwaretools#10]
During yum install of official vmware tools(vmware-tools-esx-nox, vmware-tools-esx-kmods) yum fails with a GPG check, prompting user if they want to verify key. I got the task to complete successfully by adding the following param to the yum task (disable_gpg_check: yes).

- name: Install vmware-tools.
  yum: name={{ item }} state=present
  with_items:
    - vmware-tools-esx-nox
    - vmware-tools-esx-kmods
  disable_gpg_check: yes
  when: ansible_distribution_major_version|int <= 6

**Comment by ruzickap** [comment]
Hello.

I was looking at it and I tried the following to fix it:

1. I tried to import the `http://packages.vmware.com/tools/keys/VMWARE-PACKAGING-GPG-RSA-KEY.pub` key using `rpm_key` ansible module - but it didn't help.

1. Then I tried your approach with `disable_gpg_check: yes` but it didn't help as well.

1. The only way was to turn off GPG repo key (`repo_gpgcheck=0`) inside repofile `/etc/yum.repos.d/vmware-osps.repo` and it started working...

Can you please update the role and test it again ? (It was working for me - but I just want to be sure)

Thank you...
