### ISSUE TITLE
'vmwaretools_repo_version' errors

### ISSUE THREAD

**Issue by audreyfuller** [ruzickap/ansible-role-vmwaretools#11]
I'm getting this error while trying to deploy vmware tools to SLES11. I tried to enter 10.3.5-1 manually into /defaults/main.yml but it only makes it worse 
```
TASK [ruzickap.vmwaretools : Install vmware-tools repository for SLES 11] 

FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'vmwaretools_repo_version' is undefined\n\nThe error appears to have been in '/etc/ansible/roles/ruzickap.vmwaretools/tasks/Suse.yml': line 20, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  block:\n    - name: Install vmware-tools repository for SLES 11\n      ^ here\n\nexception type: <class 'ansible.errors.AnsibleUndefinedVariable'>\nexception: 'vmwaretools_repo_version' is undefined"}
```

The RHEL/Centos task also gives an error while checking 'vmwaretools_repo_version':
```
TASK [ruzickap.vmwaretools : Get details about repository package version if vmwaretools_repo_version is undefined]

fatal: [.....]: FAILED! => {"msg": "Unexpected templating type error occurred on ({{ vmwaretools_web_page.content | regex_findall('vmware-tools-repo-RHEL' + ansible_distribution_major_version|string + '-(.*).el' + ansible_distribution_major_version|string + '.' + ansible_architecture + '.rpm') | first | string }}): expected string or buffer"}
```

Can i fix the problem myself or is it a general problem?

**Comment by ruzickap** [comment]
May I ask you what are the SLES and CentOS versions where you encountered the issues please? 
I'll try to install it myself and test it...

**Comment by audreyfuller** [comment]
Versions are Sles 11 and centos 6... :)

**Comment by ruzickap** [comment]
I was not able to reproduce the issue on CentOS 6.10.

I fixed the issue for SLES11 in: https://github.com/ruzickap/ansible-role-vmwaretools/commit/f45a31d5172082397101ba5d6a07ad4a7a02d0f2

I was testing it only on OpenSUSE 11.4 - I do not have access to real SLES11.

I tested it with ansible `2.7.9`.

Please let me know if it's working fine.

You can sun simple test by using this script: [tests/test.sh](https://github.com/ruzickap/ansible-role-vmwaretools/blob/master/tests/test.sh)
