### ISSUE TITLE
Fails if open-vm-tools is already installed

### ISSUE THREAD

**Issue by kadecole** [ruzickap/ansible-role-vmwaretools#2]
This is failing to run on my server because open-vm-tools is already installed. My suggestion is to add a test for open-vm-tools first. Or make an option for open-vm-tools or vmware tools to install so you could select which version/distribution you would like to use instead of the fallback method you are using now.

**Comment by ruzickap** [comment]
Hello. You are right - the installation of the vmware-tools will most probably fail if open-vm-tools are already installed.

I'll look at it...

Thank you

**Comment by ruzickap** [comment]
I added task to remove open-vm-tools before actual vmware-tools installation.
