### ISSUE TITLE
ini_file module usage in ansible/AWX

### ISSUE THREAD

**Issue by BongoEADGC6** [ruzickap/ansible-role-vmwaretools#27]
ERROR! couldn't resolve module/action 'ini_file'. This often indicates a misspelling, missing collection, or incorrect module path.
The error appears to be in '/runner/requirements_roles/ruzickap.vmwaretools/tasks/RedHat.yml': line 25, column 7, but may

Newer versions should be using community.general.ini_file with a dependency on the community.general collection.

**Comment by ruzickap** [comment]
Fixed.
Thank you...

**Comment by ch3codescales** [comment]
Thank so much for the quick turn around!
