### ISSUE TITLE
Falls back to openvmtools

### ISSUE THREAD

**Issue by strarsis** [ruzickap/ansible-role-vmwaretools#4]
I want to apply this role on Debian Jessie amd64 with internet connection - 
but the open-vm-tools fallback is tried instead.

```
TASK [peru.vmwaretools : include] **********************************************
skipping: [localhost] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}

TASK [peru.vmwaretools : include] **********************************************
skipping: [localhost] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}

TASK [peru.vmwaretools : include] **********************************************
included: /etc/ansible/roles/peru.vmwaretools/tasks/Debian.yml for localhost

TASK [peru.vmwaretools : Installing Open VMware Tools (open-vm-tools).] ********
[...]
```

EDIT: Apparently it will only install open-vm-tools for Debian:
https://github.com/ruzickap/ansible-role-vmwaretools/blob/master/tasks/Debian.yml#L4

But VMware Tools can be installed on Debian, too. Will this be added in near future?

**Comment by ruzickap** [comment]
Hello.

Actually I'm not sure how it is with vmware-tools and Debian. The official vmware repository contains packages only for Ubuntu: http://packages.vmware.com/tools/esx/latest/index.html

I was not able to find the packages for Debian.

I found the Debian installation steps here: http://partnerweb.vmware.com/GOSIG/Debian_8.html#installation 
-> In this case you will need a "help" from VMware vSphere Hypervisor (ESXi) - to mount cdrom with vmware-tool sources "VMwareTools-*.tar.gz" and then install kernel sources, gcc to build it.

If you know any other better way let me know about it and will have a look.

Thank you

PetrR

**Comment by strarsis** [comment]
Thank you for your answer.

VMware Workstation and VMware Player allows to mount the ISO into VM.
This role could have an option where it waits for the ISO to be inserted as virtual disk 
or just fails when the ISO isn't present, so the user can be sure that the VMware Tools are installed.
